files:
  - source: /locale/sphinx/templates/*.pot
    translation: /locale/sphinx/po/%two_letters_code%/LC_MESSAGES/%file_name%.po
    languages_mapping:
      two_letters_code:
        uk: uk_UA
        zh-CN: zh_CN
        zh-TW: zh_TW
        pt-PT: pt_PT
        pt-BR: pt_BR
        nb: nb_NO
